# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestIcecream():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_icecream(self):
    # Test name: icecream
    # Step # | name | target | value
    # 1 | open | /drive/1rCWy4A_dq-zKhcHF8i4YnBSGGGl-NIyS | 
    self.driver.get("https://colab.research.google.com/drive/1rCWy4A_dq-zKhcHF8i4YnBSGGGl-NIyS")
    # 2 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 3 | click | css=colab-run-button | 
    self.driver.find_element(By.CSS_SELECTOR, "colab-run-button").click()
    # 4 | type | css=.raw_input | 1
    self.driver.find_element(By.CSS_SELECTOR, ".raw_input").send_keys("1")
    # 5 | sendKeys | css=.raw_input | ${KEY_ENTER}
    self.driver.find_element(By.CSS_SELECTOR, ".raw_input").send_keys(Keys.ENTER)
    # 6 | type | css=.raw_input | 6
    self.driver.find_element(By.CSS_SELECTOR, ".raw_input").send_keys("6")
    # 7 | sendKeys | css=.raw_input | ${KEY_ENTER}
    self.driver.find_element(By.CSS_SELECTOR, ".raw_input").send_keys(Keys.ENTER)
    # 8 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 9 | type | css=.raw_input | 3
    self.driver.find_element(By.CSS_SELECTOR, ".raw_input").send_keys("3")
    # 10 | sendKeys | css=.raw_input | ${KEY_ENTER}
    self.driver.find_element(By.CSS_SELECTOR, ".raw_input").send_keys(Keys.ENTER)
    # 11 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 12 | type | css=.raw_input | 5
    self.driver.find_element(By.CSS_SELECTOR, ".raw_input").send_keys("5")
    # 13 | sendKeys | css=.raw_input | ${KEY_ENTER}
    self.driver.find_element(By.CSS_SELECTOR, ".raw_input").send_keys(Keys.ENTER)
    # 14 | type | css=.raw_input | 7
    self.driver.find_element(By.CSS_SELECTOR, ".raw_input").send_keys("7")
    # 15 | sendKeys | css=.raw_input | ${KEY_ENTER}
    self.driver.find_element(By.CSS_SELECTOR, ".raw_input").send_keys(Keys.ENTER)
    # 16 | mouseDown | css=.view-line:nth-child(37) | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".view-line:nth-child(37)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 17 | mouseUp | css=.view-lines | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".view-lines")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 18 | click | css=.view-lines | 
    self.driver.find_element(By.CSS_SELECTOR, ".view-lines").click()
  
